# Setup your Computer {#sec-setup}


```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

This is a tutorial on how to set up your personal computer for the course.
It guides you through the installation of several software packages.
This vignette does not assume a prior installation of `R`, so it is suitable for novice users.
You only have to perform these steps once for every computer you intend to use,
and the entire process should take approximately 30 minutes if you start from scratch.
In case some of the software is already installed on your system, you can skip those related steps.

Follow these steps in order:

1. Install [R (free)](https://CRAN.R-project.org)
1. Install ['RStudio' Desktop (Free)](https://posit.co/download/rstudio-desktop/)
1. Download the [RStudio project](https://github.com/cjvanlissa/patterns_principles_exercises/archive/refs/heads/master.zip) for this course into a folder where you'd like to keep your working files for assignments.
1. Unzip the compressed folder, open it, and open `patterns_principles_exercises.Rproj` in RStudio.
1. Once RStudio has loaded, you' ll see a panel in the bottom right labeled "Files". Click the file named `setup.R`. It will load. Select all code in this file, then either press [CONTROL+ENTER], or click the `Run` button.
